FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN go build -o main .

# Stage 2: Create the final, minimal image
FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/main .

EXPOSE 8080

ENTRYPOINT ["/app/main"]

# Define default environment variables (can be overridden by docker-compose)
ENV MONGO_URI="mongodb://localhost:27017/?replicaSet=rs0" \
    MONGO_DB_NAME="mydb"